package org.automotive.constants;

public interface EnvVarNames {
    String AUTOMOTIVE_PROCESSES_USERNAME_ENV_VAR_NAME = "AUTOMOTIVE_PROCESSES_USERNAME";
    String AUTOMOTIVE_PROCESSES_PASSWORD_ENV_VAR_NAME = "AUTOMOTIVE_PROCESSES_PASSWORD";
    String AUTORIA_PAGES_TO_SCRAPE_ENV_VAR_NAME = "AUTORIA_PAGES_TO_SCRAPE";
    String LOGGING_ERRORS_RECEIVER_ENV_VAR_NAME = "LOGGING_ERRORS_RECEIVER";
}
